### ISSUE TITLE
Upload yml file containing array

### ISSUE THREAD

**Issue by thisiscab** [onesky/i18n-one_sky-ruby#10]
Hi, 

We have locale files containing references, for example;

```
    labels:
      defaults: &labels
        save: "Save"
        edit: "Edit"

    placeholders:
      defaults:
        << : *labels

  labels: *labels
  prompts: *prompts
  hints: *hints
```

When I am trying to upload the file I get the error

```
OneSky::ApiError: {"response":"error":"Invalid hash set"}
```

Is there any way to support this?

**Comment by VLMH** [comment]
Will have a check and get back to you soon

**Comment by VLMH** [comment]
I have tested with a dummy rails app and a sample string file that has reference. There's no problem to parse the string file and upload to OneSky. Would you please provide a sample file for further testing?

p.s. If you don't wanna upload your string file here (a public repo), please send an email to support@onesky-support.mail.intercom.io and I will follow up the issue with you.

FYR, the sample file is as follow:

``` yaml
en:
  labels:
    defaults: &labels
      save: Save
      confirm: Confirm
      cancel: Cancel

  dialog:
    buttons:
      << : *labels

  common:
    buttons:
      << : *labels

  more_labels: *labels
```
